backend:
  name: test-repo
media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: markdown/posts
    create: true
    path: "{ { title } }"
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: template, label: Template, widget: string }
      - { name: body, label: Body, widget: markdown }
      - {
          label: Tags,
          name: tags,
          widget: tags,
          separator: ",",
          required: false,
        }
