# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Contributors List
      # You may pin to the exact commit or the version.
      # uses: bubkoo/contributors-list@ec4171ce9aea587579ef5ed7ca9b14fc0d9f67c9
        uses: bubkoo/contributors-list@v1.0.6
        with:
        # Your GitHub token for authentication.
          GITHUB_TOKEN: secrets.GITHUB_TOKEN
        # The repository name in form of "userName/repoName".
          userNameHeight: 12
        # Template to render SVG.
        # svgTemplate: # optional

        # Template to render user item.
        # itemTemplate: # optional, default is <a xlink:href="{{{ url }}}" class="contributor-link" target="_blank" rel="nofollow sponsored" title="{{{ name }}}" id="{{{ name }}}"><image x="{{ x }}" y="{{ y }}" width="{{ width }}" height="{{ height }}" xlink:href="{{{ avatar }}}" /></a>

        # Commit message of the github action.
        # commitMessage: # optional, default is chore: update contributors [skip ci]
    
